id: IDE440240
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:40:27+00:00'
last_modified: '2022-06-08T14:01:15.431767+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7555
  title: རྒྱལ་ཆེན་རྣམ་ཐོས་སྲས་གཅིག་ལྷག་ལྔ་ཕྲག་གསུམ་གྱི་ཕྱོགས་སྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E3E:
      image_group_id: I3CN7557
      title: ''
      total_pages: 258
      order: 1
      base_file: 8E3E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
